---
- hosts: all
  ignore_errors: 1
  gather_facts: yes
  become: True
  #become_user: root
  tasks:
  - name: Create a file
    file:
     path: /tmp/playbookfile
     mode : '0755'
     state: touch
    tags:
       - file
  - name: Check something
    command: zcskcjskchdskuj
    tags:
      - dir
    #ignore_errors: yes

  - name: Create a directory
    file:
     path: /tmp/dir
     mode: '0700'
     state: touch

  - name: Create group
    group:
     name: security   
     state: present

  - name: Create user astrid
    user:
     comment: astrid Admin
     shell: /bin/bash
     group: security
     name: astrid
    when: ansible_os_family == "Debian" or ansible_processor_nproc > 2

  - name: Check uptime
    command: uptime
  - name: Check the date
    shell: cat /etc/passwd | grep astrid